### ISSUE TITLE
Refactor the configuration file and `Config` object

### ISSUE THREAD

**Issue by garciparedes** [minos-framework/minos-python#150]
* Implement `__getitem__` on `minos.common.MinosConfig` instance. 
* Add more test for configuration Environment and Parametrized Mappers
* Create `interfaces` section in `MinosConfig` file
* Parameterize `minos.common.MinosPool` sizes
* Set default values for `MinosConfig` variables
* Add versioning strategy for `minos.common.MinosConfig`

**Comment by garciparedes** [comment]
Here is an example of the proposed refactoring:

```yaml
version: 2
name: product
injections:
  product_repository: src.ProductQueryRepository
serializer:
  client: minos.plugins.avro.AvroSerializer
  compressor: minos.common.ZlibByteCompressor
aggregate:
  transaction_repository: minos.aggregate.DatabaseTransactionRepository
  event_repository: minos.aggregate.DatabaseEventRepository
  snapshot_repository: minos.aggregate.DatabaseSnapshotRepository
saga:
  manager: minos.saga.SagaManager
databases:
  default:
    lock_pool: minos.common.DatabaseLockPool
    client_pool: minos.common.DatabasePool
    client: minos.plugins.aiopg.PostgresClient
    pool_size: 10
    database: product_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
  saga:
    client: minos.plugins.lmbb.LmdbClient
    path: ./product.lmdb
  query:
    client: minos.plugins.aiopg.PostgresClient
    database: product_query_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
interfaces:
  http:
    port: minos.networks.BrokerPort
    connector:
      client: minos.plugins.aiohttp.AioHttpConnector
      port: 8081
  broker:
    publisher:
      client: minos.plugins.kafka.KafkaBrokerPublisher
      pool_size: 10
      queue:
        client: minos.clients.aiopg.PostgresBrokerPublisherQueue
        records: 1000
        retry: 2
    subscriber:
      client: minos.plugins.kafka.KafkaBrokerSubscriber
      pool_size: 10
      queue:
        client: minos.clients.aiopg.PostgresBrokerSubscriberQueue
        records: 1000
        retry: 2
      idempotent: minos.clients.aiopg.PostgresBrokerPublisherDuplicateDetector
    host: localhost
    port: 9092
  periodic:
    port: minos.networks.PeriodicTaskPort
discovery:
  connector: minos.networks.DiscoveryConnector
  client: minos.plugins.minos_discovery.MinosDiscoveryClient
  host: localhost
  port: 5567
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.networks.OpenApiService
  - minos.networks.AsyncApiService
  - minos.aggregate.TransactionService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.queries.ProductQueryService
  - src.commands.ProductCommandService
```

**Comment by garciparedes** [comment]
Here is an example of the proposed refactoring:

```yaml
version: 2
name: product
injections:
  product_repository: src.ProductQueryRepository
serializer:
  client: minos.plugins.avro.AvroSerializer
  compressor: minos.common.ZlibByteCompressor
aggregate:
  transaction_repository: minos.aggregate.DatabaseTransactionRepository
  event_repository: minos.aggregate.DatabaseEventRepository
  snapshot_repository: minos.aggregate.DatabaseSnapshotRepository
saga:
  manager: minos.saga.SagaManager
databases:
  default:
    lock_pool: minos.common.DatabaseLockPool
    client_pool: minos.common.DatabasePool
    client: minos.plugins.aiopg.PostgresClient
    pool_size: 10
    database: product_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
  saga:
    client: minos.plugins.lmbb.LmdbClient
    path: ./product.lmdb
  query:
    client: minos.plugins.aiopg.PostgresClient
    database: product_query_db
    user: minos
    password: min0s
    host: localhost
    port: 5432
interfaces:
  http:
    port: minos.networks.BrokerPort
    connector:
      client: minos.plugins.aiohttp.AioHttpConnector
      port: 8081
  broker:
    port: minos.networks.BrokerPort
    common:
      host: localhost
      port: 9092
      queue:
        records: 1000
        retry: 2
    publisher:
      client: minos.plugins.kafka.KafkaBrokerPublisher
      pool_size: 10
      queue:minos.clients.aiopg.PostgresBrokerPublisherQueue
    subscriber:
      client: minos.plugins.kafka.KafkaBrokerSubscriber
      pool_size: 10
      queue:minos.clients.aiopg.PostgresBrokerSubscriberQueue
      idempotent: minos.clients.aiopg.PostgresBrokerPublisherDuplicateDetector
  periodic:
    port: minos.networks.PeriodicTaskPort
discovery:
  connector: minos.networks.DiscoveryConnector
  client: minos.plugins.minos_discovery.MinosDiscoveryClient
  host: localhost
  port: 5567
saga: 
  manager: minos.saga.SagaManager
aggregate:
  entities:
    - src.Order
    - src.OrderItem
  repositories:
    event: minos.aggregate.PostgreSqlEventRepository
    snapshot: minos.aggregate.PostgreSqlSnapshotRepository
    transaction: minos.aggregate.PostgreSqlTransactionRepository
routers:
  - minos.networks.BrokerRouter
  - minos.networks.PeriodicRouter
  - minos.networks.RestHttpRouter
middleware:
  - minos.saga.transactional_command
services:
  - minos.networks.SystemService
  - minos.networks.OpenApiService
  - minos.networks.AsyncApiService
  - minos.aggregate.TransactionService
  - minos.aggregate.SnapshotService
  - minos.saga.SagaService
  - src.queries.ProductQueryService
  - src.commands.ProductCommandService
```
