### ISSUE TITLE
Add query_repository paramter to MinosConfig

### ISSUE THREAD

**Issue by andrea-mucci** [minos-framework/minos-python#162]
**Is your feature request related to a problem? Please describe.**
the MinosConfig must support the a new parameter
query_repository

**Describe the solution you'd like**
the query_service paramter have the following parameters

```yaml
query_repository:
  database: product_db
  user: postgres
  password: ""
  host: localhost
  port: 5432
```
