### ISSUE TITLE
Create `interfaces` section in `MinosConfig` file

### ISSUE THREAD

**Issue by garciparedes** [minos-framework/minos-python#41]
<a href="https://github.com/garciparedes"><img src="https://avatars.githubusercontent.com/u/5640366?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [garciparedes](https://github.com/garciparedes)**
_Wednesday Sep 29, 2021 at 10:40 GMT_
_Originally opened as https://github.com/Clariteia/minos_microservice_common/issues/594_

----

Currently `rest` and `broker` entries in the configuration file are independent. This issue is intended to create a parent section that groups them.

Here is an example before and after the refactor:
* Before:
```yaml
service:
    ...
rest:
    host: 0.0.0.0
    port: 8000
broker:
    host: kafka
    port: 9092
    queue:
        ...
...
```
* After:
```yaml
service:
    ...
interfaces:
    rest:
        host: 0.0.0.0
        port: 8000
    broker:
        host: kafka
        port: 9092
        queue:
            ...
...
```
